#server:
#  port: 8080
#
#spring:
#  application:
#    name: postapi
#
#  datasource:
#    url: jdbc:h2:file:./database/historyPost
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: admin
#
#  h2:
#      console:
#        enabled: true
#      tcpServer:
#        enabled: true
#
#  jpa:
#      hibernate:
#        ddl-auto: create-drop
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect
#          show_sql: true
#          format_sql: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    preferIpAddress: true
